# Files
WEIGHTS_FILENAME = './model/model.pth'
SCORE_DATA_FILENAME = './data.csv'

# Game
BLOCK_SIZE = 20
DIRECTIONS_QUANTITY = 4
FRAME_RESTRICTION = 1000

# Train
MAX_MEMORY = 100_000
BATCH_SIZE = 1000
LR = 0.001
AVAILABLE_DIRECTIONS_QUANTITY = 3
INPUT_LAYER_SIZE = 11
HIDDEN_LAYER_SIZE = 256
OUTPUT_LAYER_SIZE = 3